---
- name: install tomcat using loops
  hosts: all
  tasks: 
    - name:  install tomcat10 & tomcat10-admin using loops
      apt: 
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present, c: yes}
        - {a: tomcat10-admin,b: present, c: yes}
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat10
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat
      service: 
         name: tomcat10
         state: restarted
    - name: pause for 20 seconds
      pause: 
        seconds: 20 
    - name: check response of tomcat
      uri:
        url: "{{item}}"
        status_code: 200
      with_items: 
          - http://98.92.200.148:9090
          - http://3.238.31.178:9090

...
