---
- name: Implementing host scope variables
  hosts: 172.31.28.31
  tasks:
    - name: User creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"

