---
- name: Install jenkis and req s/w's
  hosts: jenkinsserver
  tasks:
    - name: install req s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-17-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: download jenkins.war file
      get_url:
         url: https://get.jenkins.io/war-stable/2.528.3/jenkins.war
         dest: /home/ubuntu
- name: setup tomcat on qa & prod servers
  hosts: servers
  tasks:
    - name: install tomcat on both qa & prod servers
      apt: 
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: yes}
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
      notify: restart tomcat
  handlers: 
     - name: restart tomcat
       service:
          name: tomcat10
          state: restarted    


...
