---
- name: Implenting play scope variables 
  hosts: all
  vars: 
    a: tomcat10
    b: present
    c: yes
  tasks:
    - name: Install/uninstall s/w apps
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}" 

...
