---
- name: Install got on all servers
  hosts: all
  tasks:
    - name: install git on all ubuntu using apt
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install git on all redhat using yum
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"  
