---
- name: Create users and create file/dir in users home dir
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file/dir in user home dir
      file: 
        name: "{{d}}"
        state: "{{e}}"
...
