---
- name: Configure Apache/HTTPD based on Linux flavour
  hosts: all
  vars:
    apache_pkg: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
    apache_service: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"

  tasks:
    - name: Install Apache/HTTPD
      package:
        name: "{{ apache_pkg }}"
        state: present
      register: install_status

    - name: Deploy index.html
      copy:
        content: "Welcome to my IntelliQ"
        dest: /var/www/html/index.html
    
    - name: Restart Apache
      service:
        name: "{{ apache_service }}"
        state: restarted


    - name: Check Apache/HTTPD response on all servers
      uri:
        url: "{{ item }}"
        status_code: 200
      loop:
        - http://172.31.1.21
        - http://172.31.3.178
        - http://172.31.12.134
