---
- name: Implementing all
  hosts: all
  tasks:
    - name: Create user
      user:
        name: Sravya
        password: Sravya
      tags: user_creation    
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation
    - name: Copy password file
      copy:
        src: /etc/passwd
        dest: /tmp
...          


