---
- name: change permissions for empty files
  hosts: all
  tasks: 
    - name: capture the file info
      stat:
        path: /tmp/file3
      register: a
    - name: display o/p of above module
      debug: 
        var: a
    - name: changhe permissions if file is empty
      file:
        name: /tmp/file3
        mode: 777
        state: touch
      when: a.stat.size == 0    
...
