---
- name: capture os info on all servers
  hosts: all
  tasks:
    - name: diplay os name
      debug:
        var: ansible_distribution
    - name: Capture OS version
      debug:
        var: ansible_distribution_version
...          
