---
- name: intalling apache2
  hosts: all
  tasks: 
    - name:
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit html file
      copy:
        content: "IntelliqIT"
        dest: /vars/www/html/index.html
    - name: Restart apache2
      service:
         name: apache2
         state: restarted
    - name: check the status in S1
      uri:
        url: http://172.31.1.21
        status_code: 200
    - name: check the status in S2
      uri:
        url: http://172.31.3.178
        status_code: 200
...
