---
- name: conf apache/httpd based on linus flavour
  hosts: all
  tasks:
    - name: install apache on ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu" 
    - name: install httpd on redhat servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat" 
    - name: Edit index.html file
      copy:
        content: "Welcome to intelliq"
        dest: /var/www/html/index.html
    - name: restart apache on ubunut servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restart httpd on redhat servers
      service: 
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: pause for 20 secs
      pause:
        seconds: 20
    - name: check apache2/httpd response 
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.1.21
        - http://172.31.3.178
        - http://172.31.12.134





...
