---
- name: fetch file1 from server1
  hosts: 172.31.1.21
  tasks:
    - name: Fetch the file
      fetch: 
        src: file1
        dest: /tmp
- name: copy file to server2
  hosts: 172.31.3.178
  tasks:
    - name: copy file 
      copy:
        src: /tmp/172.31.1.21/file1
        dest: /home/ubuntu


